config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :line_items
  resources :carts
  resources :products
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(product_id: product.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

end

app/models/concerns/current_cart.rb
module CurrentCart

  private
    def set_cart
      @cart = Cart.find(session[:cart_id])
      rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :title, :quantity, :category, :color, :price, presence:true 
    validates :description, length: {maximum: 1000, too_long: "%{count} charecters is the maximum allowed. "}
    validates :title,length: {maximum: 1000, too_long: "%{count} charecters is the maximum allowed. "}

    CATEGORY = %w{ Clothing Footwear Accessories Bags Sportswear Fragnances Laptops }
    COLOR = %w{ Black White Red Yellow Green Blue Orange Grey }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  validates :email, :password, presence:true 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include CurrentCart
    before_action :set_cart
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]

  def index
    @line_items = LineItem.all
  end

  def show
  end

  def new
    @line_item = LineItem.new
  end

  def edit
  end

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Product added to cart.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = if params[:category].present?
    Product.where('category = ?', params[:category])
    elsif params[:color].present?
    Product.where('color = ?', params[:color])
    else    
    Product.all.order("created_at desc")
    end
  end

  def show
  end

  def new
    @product = current_user.products.build
  end

  def edit
  end

  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :quantity, :category, :color, :price, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private 
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def cart_count_over_one
        if @cart.line_items.count>0
            return "<span>#{@cart.line_items.count}</span>".html_safe
        end
    end

    def cart_has_items
        return @cart.line_items.count > 0
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.haml
= simple_form_for(@cart) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
  .form-actions
    = f.button :submit

app/views/carts/edit.html.haml
%h1 Editing Cart
= render 'form', cart: @cart
= link_to 'Show', @cart
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%p#notice= notice
%h1 Carts
%table
  %thead
    %tr
      %th{colspan: "3"}
  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New Cart
= render 'form', cart: @cart
= link_to 'Back', carts_path

app/views/carts/show.html.haml
.keep-shopping.pv1.mt4.has-text-right
  = link_to 'Keep Shopping', products_path, class: 'button is-warning'
%hr/
%section.section
  = render(@cart.line_items)
  .columns
    .column
      = button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger"
    .column.total.has-text-right
      %h4.title.is-4
        %span.f5.has-text-grey Total:
        = number_to_currency(@cart.total_price)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Product Catalogue
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body{class: "#{yield (:body_class)}"}
    - if flash[:notice]
      .notification.is-success.global-notification
        %p.notice= notice
    - if flash[:alert]
      .notification.is-danger.global-notification
        %p.alert= alert
    %nav.navbar.is-warning{"aria-label" => "main navigation", role: "navigation"}
      .navbar-brand
        = link_to root_path, class:"navbar-item" do
          %h1.title.is-5 Product Catalogue
        .navbar-burger.burger{"data-target" => "navbar"}
          %span
          %span
          %span
      #navbar.navbar-menu
        .navbar-end
          .navbar-item
            .field.is-grouped
              - if cart_has_items && user_signed_in?
                = link_to cart_path(@cart), class:"navbar-item button is-warning" do
                  %span.icon.is-small
                    %i.fa.fa-shopping-cart
                  %span
                    Cart
                    \#{cart_count_over_one}
              - if user_signed_in?
                - if warden.user.admin == true
                  = link_to 'Products', new_product_path, class: "navbar-item button is-dark"
                - else
                  = link_to 'Products', products_path, class: "navbar-item button is-dark"
                .navbar-item.has-dropdown.is-hoverable
                  = link_to 'Account', "#", class: "navbar-link"
                  .navbar-dropdown.is-right
                    = link_to current_user.name, "#", class:"navbar-item"
                    = link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item"
              - else
                = link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning"
                = link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"
    = yield(:header)
    .container
      = yield

app/views/line_items/_form.html.haml
= simple_form_for(@line_item) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.association :product
    = f.association :cart
  .form-actions
    = f.button :submit

app/views/line_items/_line_item.html.haml
.columns.align-items-center
  .column.is-1
    = line_item.quantity
  .column.is-2
    %figure.is-128x128.image
      = image_tag(line_item.product.image_url(:thumb))
  .column.is-9
    %strong= line_item.product.title
    .columns.align-items-center
      .content.column.is-9
        = truncate(line_item.product.description, length: 140)
      .column.is-3.has-text-right
        %strong.f4= number_to_currency(line_item.total_price)
.has-text-right
  = link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-small mb4"
= succeed "" do
  %hr/

app/views/line_items/edit.html.haml
%h1 Editing Line Item
= render 'form', line_item: @line_item
= link_to 'Show', @line_item
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%p#notice= notice
%h1 Line Items
%table
  %thead
    %tr
      %th Product
      %th Cart
      %th{colspan: "3"}
  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product
        %td= line_item.cart
        %td= link_to 'Show', line_item
        %td= link_to 'Edit', edit_line_item_path(line_item)
        %td= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Line Item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New Line Item
= render 'form', line_item: @line_item
= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice
%p
  %strong Product:
  = @line_item.product
%p
  %strong Cart:
  = @line_item.cart
= link_to 'Edit', edit_line_item_path(@line_item)
= link_to 'Back', line_items_path

app/views/products/_form.html.haml
.columns
  .column.is-8.is-centered
    = simple_form_for(@product) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      %br/
      .columns
        .field.column.is-9
          = f.input :title, required: true, input_html: { class: "input"}, wrapper: false
        .field.column
          = f.input :price, required: true, wrapper: false
      .field
        = f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false
      .columns
        .field.column.is-4
          %label Quantity
          = f.input_field :quantity, wrapper: false
        .field.column.is-4
          %label Category
          .control.has-icons-left
            %span.select
              = f.input_field :category, collection: Product::CATEGORY, prompt: "Select category"
        .field.column
          %label Color
          .control.has-icons-left
            %span.select
              = f.input_field :color, collection: Product::COLOR, prompt: "Select color"
      .field
        .control
          %label Add images
          .file
            %label.file-label
              = f.input :image, as: :file, input_html: { class:"file-input product-image" }, label: false, wrapper: false
              %span.file-cta
                %span.file-icon
                  %i.fa.fa-upload
                %span.file-label Choose a file…
      %hr/
      .field.is-grouped
        .control
          = f.button :submit, class: 'button is-warning'
          = link_to 'Cancel', products_path, class:'button is-light'

app/views/products/edit.html.haml
- content_for :header do
  .container
    %h1.title
      Editing Product
.pv4
  = render 'form', product: @product

app/views/products/index.html.haml
- content_for :header do
  .container
    %h1.title
      Browsing products
%hr/
%br/
.row
  .col-md-3
    %br/
    %h2 Categories
    %hr/
    - Product.distinct(:category).pluck(:category).each do |category|
      %h3.fw7.f6.title
        = link_to category, products_path(:category => category)
    %nbsp
      %hr/
      %h2 Color
      %hr/
      - Product.distinct(:color).pluck(:color).each do |color|
        %h3.fw7.f6.title
          = link_to color, products_path(:color => color)
  - @products.each do |product|
    .col-sm-6.col-md-3
      .thumbnail
        = link_to image_tag(product.image_url(:thumb)), product
      .caption
        %h3
          = link_to product.title, product
        %p
          = link_to product.description, product
        %p
          %b
            = number_to_currency(product.price)
            %b
        - if user_signed_in? && warden.user.admin == true
          = link_to 'Edit', edit_product_path(product), class: "button is-small"
          = link_to 'Delete', product, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small"
    %nbsp

app/views/products/new.html.haml
- content_for :header do
  .container
    %h1.title
      New Product
%hr/
.pv4
  = render 'form', product: @product

app/views/products/show.html.haml
- content_for :body_class, 'bg-light'
%section.section.instrument-show
  .columns
    .column.is-8
      %h1.title.is-2= @product.title
      .feature-image
        = image_tag(@product.image_url)
      .content.pa4.mt3.bg-white.border-radius-3
        %h3.subtitle.is-4 Description
        = @product.description
        %h3.subtitle.is-4.pt5 Product Specs
        %table.table.is-narrow
          - if @product.category
            %tr
              %td.has-text-weight-bold Category:
              %td= @product.category
          - if @product.color
            %tr
              %td.has-text-weight-bold Color:
              %td= @product.color
          - if @product.quantity
            %tr
              %td.has-text-weight-bold Quantity:
              %td= @product.quantity
    %br/
    .column.is-3.is-offset-1
      .bg-white.pa4.border-radius-3
        %h4.title.is-5.has-text-centered= number_to_currency(@product.price)
        = button_to 'Add to cart', line_items_path(product_id: @product), class: 'button is-warning add-to-cart'